export * from "./nitrogen.controller"
export * from "./kalium.controller"
export * from "./phospor.controller"
export * from "./ph.controller"
export * from "./temperature.controller"
export * from "./moisture.controller"
export * from "./conductivity.controller"